version: '2.1'
services:
    yona-db:
        image: mariadb:10.2.14
        volumes:
            - ${PWD}/db/conf:/etc/mysql/conf.d
            - ${PWD}/db/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=yona
            - MYSQL_USER=yona
            - MYSQL_PASSWORD=yona
            - MYSQL_ROOT_PASSWORD=maria
        privileged: true
        ports:
            - "3306:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=yona --password=yona --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 10

    yona:
        image: inlineno1/yona:1.9.1
        volumes:
            - ${PWD}/app/data:/opt/yona/data
        privileged: true
        ports:
            - "9000:9000" 
        links:
            - yona-db
        depends_on:
            yona-db:
                condition: service_healthy
